name: Build and Deploy
on:
  push:
    branches:
      - 'master'
      - 'main'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Build
        run: |
          make install-python-requirements
          make generate-site
      - name: Deploy
        uses: actions/deploy-pages@v4
